-- 150 registros de la tabla Sucursal
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (1,'Farmacia San Pedro','Carranza',59,86,'Polanco','Sinaloa','+08210716236');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (2,'Farmacia San Antonio','Callejón del Beso',13,3,'La Joya','Yucatán','+94957180491');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (3,'Farmacia San Antonio','Morelos',20,42,'Coyoacan','Chihuahua','+538077455600');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (4,'Farmacia San Pablo','Benito Juárez',86,81,'Lomas de Chapultepec','Zacatecas','+6550102079843');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (5,'Farmacia San Lucas','Benito Juárez',84,62,'La Joya','Aguascalientes','+611441979365');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (6,'Farmacia del Sol','Lázaro Cárdenas',77,65,'Condesa','Hidalgo','+3109828614885');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (7,'Farmacia San Antonio','Galeana',48,72,'Roma Norte','Tlaxcala','+344590195088');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (8,'Farmacia del Sol','Lázaro Cárdenas',86,74,'Cuajimalpa','Baja California','+08769398830');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (9,'Farmacia La Paz','Zaragoza',69,55,'Napoles','Zacatecas','9014093973');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (10,'Farmacia San Pedro','Galeana',27,85,'San Pedro','Coahuila','9255042981');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (11,'Farmacia San Rafael','Callejón del Beso',90,70,'Del Valle','Sinaloa','8223790840');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (12,'Farmacia San Juan','Hidalgo',6,38,'Napoles','Aguascalientes','6478081472');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (13,'Farmacia San Lorenzo','Lázaro Cárdenas',23,48,'Interlomas','Jalisco','7015765922');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (14,'Farmacia San Vicente','Independencia',61,5,'Condesa','Aguascalientes','4844417285');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (15,'Farmacia San Vicente','Benito Juárez',82,60,'Lomas de Chapultepec','Aguascalientes','5285140555');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (16,'Farmacia San Lucas','Morelos',69,39,'Del Valle','Colima','9611067357');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (17,'Farmacia del Sol','Obregón',9,73,'Roma Norte','Veracruz','0643521706');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (18,'Farmacia San Pedro','Madero',19,68,'Interlomas','Michoacán','0597937667');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (19,'Farmacia Guadalajara','Lázaro Cárdenas',56,66,'Coyoacan','Veracruz','+8806823037979');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (20,'Farmacia San Antonio','Independencia',11,8,'Satelite','Querétaro','3720999875');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (21,'Farmacia San Pablo','Carranza',68,83,'Tlalpan','Aguascalientes','+714349351772');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (22,'Farmacia Santa Ana','Madero',38,54,'Napoles','Durango','4634869344');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (23,'Farmacia San José','Callejón del Beso',59,25,'Lomas de Chapultepec','Michoacán','2655697651');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (24,'Farmacia San Miguel','Galeana',65,80,'Lomas de Chapultepec','Querétaro','+421252145009');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (25,'Farmacia San Ignacio','Morelos',42,72,'Interlomas','Zacatecas','9155127129');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (26,'Farmacia San José','Madero',69,22,'Interlomas','Puebla','8761919707');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (27,'Farmacia La Paz','Carranza',62,96,'San Pedro','Nuevo León','6170211183');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (28,'Farmacia La Paz','Hidalgo',2,96,'Condesa','Morelos','2149150917');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (29,'Farmacia San Vicente','Zaragoza',60,12,'Interlomas','Jalisco','6602846907');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (30,'Farmacia San Ignacio','Zaragoza',53,8,'Satelite','Tlaxcala','8519881249');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (31,'Farmacia Guadalajara','Zaragoza',45,92,'Napoles','Guerrero','4813276575');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (32,'Farmacia Guadalajara','Galeana',25,23,'Tlalpan','Oaxaca','+129215665716');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (33,'Farmacia San Pablo','Guerrero',81,96,'San Pedro','Jalisco','7832252064');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (34,'Farmacia del Sol','Carranza',81,9,'Lomas de Chapultepec','Morelos','4628902998');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (35,'Farmacia San José','Zaragoza',58,76,'Polanco','Querétaro','4140870066');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (36,'Farmacia San Pablo','Lázaro Cárdenas',27,76,'Polanco','Durango','+085517579147');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (37,'Farmacia Guadalajara','Callejón del Beso',37,75,'Lomas de Chapultepec','Guanajuato','3136430537');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (38,'Farmacia San Vicente','Madero',8,90,'Condesa','San Luis Potosí','0692315036');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (39,'Farmacia San Pablo','Juárez',13,38,'La Joya','Guanajuato','2839021337');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (40,'Farmacia San Vicente','Callejón del Beso',41,35,'La Joya','Chiapas','+06152511964');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (41,'Farmacia San Juan','Galeana',51,58,'Cuajimalpa','Quintana Roo','1961206960');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (42,'Farmacia San Pablo','Benito Juárez',51,6,'Tlalpan','México','8195198537');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (43,'Farmacia San Miguel','Carranza',21,75,'Coyoacan','Tlaxcala','5564244845');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (44,'Farmacia San Pablo','Hidalgo',77,9,'Lomas de Chapultepec','Quintana Roo','+6711623412103');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (45,'Farmacia San Lucas','Independencia',49,58,'Tlalpan','Durango','9754439650');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (46,'Farmacia San Juan','Juárez',56,24,'Cuajimalpa','Colima','+52597134570');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (47,'Farmacia San Lorenzo','Callejón del Beso',30,97,'La Joya','Durango','+2040706069486');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (48,'Farmacia San Vicente','Benito Juárez',37,99,'Polanco','Chihuahua','+547580907836');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (49,'Farmacia San José','Revolución',80,65,'Del Valle','México','+98481053111');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (50,'Farmacia San Ignacio','Madero',40,63,'La Joya','Chihuahua','+356182812109');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (51,'Farmacia San Pedro','Hidalgo',48,53,'Del Valle','Yucatán','1374663163');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (52,'Farmacia San Pedro','Madero',29,99,'Interlomas','San Luis Potosí','5647184824');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (53,'Farmacia San Vicente','Revolución',43,20,'Lomas de Chapultepec','Jalisco','+544025355702');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (54,'Farmacia Guadalajara','Madero',94,44,'Cuajimalpa','Tlaxcala','7695161549');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (55,'Farmacia San Lucas','Madero',88,56,'Bosques de Chapultepec','Durango','+23876157834');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (56,'Farmacia San Rafael','Callejón del Beso',97,21,'Del Valle','Tabasco','+7541433553452');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (57,'Farmacia del Sol','Revolución',3,80,'Tlalpan','Colima','+4331724434499');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (58,'Farmacia Santa Ana','Carranza',88,97,'Coyoacan','Puebla','+661716310992');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (59,'Farmacia San Vicente','Allende',78,69,'La Joya','Baja California Sur','+734493651168');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (60,'Farmacia San Ignacio','Hidalgo',67,70,'San Pedro','Morelos','+2970456549633');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (61,'Farmacia Santa Ana','Galeana',6,57,'Polanco','Tamaulipas','+7720466145107');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (62,'Farmacia San Juan','Juárez',32,82,'Cuajimalpa','Jalisco','+89683351641');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (63,'Farmacia San Pablo','Allende',19,12,'Interlomas','México','7390572612');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (64,'Farmacia San Ignacio','Revolución',3,67,'La Joya','Guerrero','+2814505169375');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (65,'Farmacia San José','Revolución',73,83,'Polanco','Nuevo León','9885835884');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (66,'Farmacia San Pablo','Benito Juárez',51,18,'La Joya','Coahuila','8019660121');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (67,'Farmacia San Vicente','Independencia',86,100,'Cuajimalpa','Durango','0390208442');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (68,'Farmacia San Ignacio','Lázaro Cárdenas',5,73,'Condesa','Nuevo León','6688731057');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (69,'Farmacia San Juan','Benito Juárez',67,72,'Del Valle','Jalisco','+5172101574431');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (70,'Farmacia del Sol','Zaragoza',55,63,'Roma Norte','Oaxaca','9510752560');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (71,'Farmacia San Pedro','Lázaro Cárdenas',100,28,'Roma Norte','Colima','8931029784');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (72,'Farmacia San Lucas','Juárez',79,89,'Condesa','Colima','9586055781');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (73,'Farmacia San Pablo','Juárez',51,39,'Lomas de Chapultepec','Yucatán','7906947305');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (74,'Farmacia San Lucas','Allende',75,50,'Polanco','Tlaxcala','2775219246');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (75,'Farmacia San José','Lázaro Cárdenas',84,28,'Cuajimalpa','Guanajuato','7748284546');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (76,'Farmacia San Juan','Hidalgo',36,8,'Bosques de Chapultepec','Baja California','5378448384');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (77,'Farmacia San Vicente','Carranza',30,25,'Coyoacan','Guanajuato','+693669424894');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (78,'Farmacia San Rafael','Galeana',53,42,'Condesa','Aguascalientes','5577989091');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (79,'Farmacia La Paz','Juárez',74,66,'Condesa','Aguascalientes','+583557037885');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (80,'Farmacia San Vicente','Lázaro Cárdenas',75,46,'Cuajimalpa','Nuevo León','2564585123');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (81,'Farmacia San Antonio','Revolución',79,37,'Tlalpan','Baja California','6562902856');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (82,'Farmacia San Rafael','Independencia',45,34,'Condesa','Nayarit','+53571216096');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (83,'Farmacia San José','Hidalgo',57,30,'Santa Fe','Aguascalientes','2611659048');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (84,'Farmacia Santa Ana','Morelos',80,19,'Condesa','Colima','+18451611698');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (85,'Farmacia San Juan','Revolución',93,84,'Interlomas','Quintana Roo','9205306673');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (86,'Farmacia San Juan','Allende',99,58,'San Pedro','Tlaxcala','+770849327663');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (87,'Farmacia San Miguel','Independencia',76,62,'La Joya','Tamaulipas','+21212983245');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (88,'Farmacia San Lorenzo','Independencia',26,91,'Satelite','Guerrero','+541146042628');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (89,'Farmacia San Juan','Obregón',75,33,'Del Valle','Baja California','5242897039');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (90,'Farmacia San Antonio','Benito Juárez',28,98,'Satelite','Aguascalientes','2347970726');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (91,'Farmacia San Lucas','Zaragoza',63,98,'Condesa','Nayarit','8757858253');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (92,'Farmacia San Rafael','Revolución',58,70,'Roma Norte','Durango','7158707297');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (93,'Farmacia San Miguel','Madero',91,40,'Lomas de Chapultepec','Durango','7797060159');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (94,'Farmacia San Miguel','Obregón',12,51,'Napoles','México','+225930014690');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (95,'Farmacia San Pedro','Hidalgo',59,29,'Interlomas','Puebla','0109879452');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (96,'Farmacia San Pablo','Callejón del Beso',96,6,'Satelite','Morelos','+4902861957648');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (97,'Farmacia San Lorenzo','Galeana',86,82,'Napoles','Colima','0324077894');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (98,'Farmacia San Pedro','Benito Juárez',68,74,'Coyoacan','Nayarit','+1143559083642');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (99,'Farmacia San Rafael','Revolución',22,75,'Interlomas','Guerrero','2729044681');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (100,'Farmacia del Sol','Carranza',71,38,'Tlalpan','Hidalgo','+602876243341');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (101,'Farmacia San Pedro','Allende',33,14,'Satelite','Yucatán','1933114848');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (102,'Farmacia San Pedro','Independencia',4,34,'Condesa','Sonora','8197378088');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (103,'Farmacia San Miguel','Callejón del Beso',2,86,'La Joya','Veracruz','+22099695115');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (104,'Farmacia San Pablo','Guerrero',30,19,'Del Valle','Guerrero','+39790602491');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (105,'Farmacia San Lucas','Guerrero',80,65,'Coyoacan','Guanajuato','+021506914010');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (106,'Farmacia San Ignacio','Revolución',28,13,'Del Valle','Tabasco','2195646932');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (107,'Farmacia San Vicente','Lázaro Cárdenas',46,17,'Polanco','Zacatecas','+4199935587853');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (108,'Farmacia Santa Ana','Zaragoza',43,7,'Bosques de Chapultepec','Quintana Roo','+69264730593');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (109,'Farmacia San Lucas','Obregón',40,81,'Tlalpan','Aguascalientes','5340474301');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (110,'Farmacia San José','Lázaro Cárdenas',82,82,'Cuajimalpa','Oaxaca','5735035990');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (111,'Farmacia San Pablo','Lázaro Cárdenas',40,10,'Santa Fe','Chihuahua','5397830323');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (112,'Farmacia Guadalajara','Hidalgo',57,59,'Coyoacan','Jalisco','+029803770404');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (113,'Farmacia San Lorenzo','Allende',8,64,'La Joya','Jalisco','7168454532');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (114,'Farmacia Guadalajara','Allende',3,61,'Coyoacan','Jalisco','+001800827309');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (115,'Farmacia San Rafael','Allende',58,11,'Cuajimalpa','San Luis Potosí','8720593714');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (116,'Farmacia San Rafael','Independencia',96,30,'Tlalpan','Tabasco','+880049903419');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (117,'Farmacia San Rafael','Callejón del Beso',88,89,'Polanco','Aguascalientes','6825488383');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (118,'Farmacia del Sol','Galeana',78,21,'Santa Fe','Coahuila','4129041061');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (119,'Farmacia Santa Ana','Guerrero',31,74,'Interlomas','Guerrero','2356426788');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (120,'Farmacia San Miguel','Hidalgo',60,5,'Tlalpan','Yucatán','+688149025690');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (121,'Farmacia San Vicente','Morelos',93,35,'San Pedro','Baja California','+36068091659');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (122,'Farmacia del Sol','Zaragoza',81,45,'Napoles','Baja California Sur','7057466512');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (123,'Farmacia San Juan','Obregón',31,22,'Santa Fe','Zacatecas','7741036138');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (124,'Farmacia San Juan','Guerrero',35,16,'San Pedro','Tamaulipas','+638958025988');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (125,'Farmacia San Pablo','Madero',64,11,'Santa Fe','Tlaxcala','3834684070');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (126,'Farmacia Guadalajara','Guerrero',58,86,'Polanco','Quintana Roo','+352756785583');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (127,'Farmacia San Vicente','Galeana',28,80,'Del Valle','Guanajuato','+589665235808');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (128,'Farmacia San Miguel','Morelos',82,44,'Polanco','Guerrero','+882714436564');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (129,'Farmacia Santa Ana','Benito Juárez',28,58,'Napoles','Colima','2993041182');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (130,'Farmacia La Paz','Guerrero',93,72,'Coyoacan','Veracruz','+8439036038197');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (131,'Farmacia San Pedro','Benito Juárez',37,76,'Polanco','Zacatecas','+7923609084818');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (132,'Farmacia La Paz','Carranza',1,32,'Condesa','Durango','+24900958865');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (133,'Farmacia La Paz','Galeana',91,83,'Coyoacan','Morelos','5564052439');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (134,'Farmacia San Lorenzo','Obregón',89,50,'Bosques de Chapultepec','Zacatecas','+49425822923');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (135,'Farmacia del Sol','Zaragoza',51,86,'Tlalpan','Nuevo León','+08379324188');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (136,'Farmacia Guadalajara','Morelos',39,51,'Satelite','Sonora','+36301808134');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (137,'Farmacia San Pablo','Guerrero',39,83,'Tlalpan','Nayarit','1477754174');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (138,'Farmacia San Juan','Obregón',99,71,'Condesa','Hidalgo','9168298859');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (139,'Farmacia San Ignacio','Obregón',55,93,'Bosques de Chapultepec','Sinaloa','+19865829116');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (140,'Farmacia Santa Ana','Revolución',61,95,'Bosques de Chapultepec','Puebla','1254695591');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (141,'Farmacia San Lorenzo','Morelos',59,61,'Coyoacan','Jalisco','9515376435');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (142,'Farmacia San Juan','Carranza',91,93,'Condesa','Michoacán','6654144267');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (143,'Farmacia San Ignacio','Obregón',75,73,'Condesa','México','3532477888');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (144,'Farmacia San Ignacio','Juárez',39,21,'Del Valle','Colima','+640465823517');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (145,'Farmacia Guadalajara','Galeana',66,22,'Interlomas','Jalisco','+67581520954');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (146,'Farmacia del Sol','Madero',75,58,'Cuajimalpa','Chiapas','5703862541');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (147,'Farmacia Guadalajara','Callejón del Beso',27,61,'Tlalpan','Baja California Sur','0579837472');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (148,'Farmacia Guadalajara','Benito Juárez',93,93,'Roma Norte','Baja California Sur','7852957147');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (149,'Farmacia San Pedro','Allende',28,10,'Tlalpan','Coahuila','+41781759115');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (150,'Farmacia San Vicente','Independencia',66,45,'Coyoacan','Colima','5866875784');


--150 registros de la tabla Clinica


--150 registros de la tabla Medico


--150 registros de la tabla Telefonos_Medico


-- Tablas necesarias para ejecutar el script Query.sql

