-- 150 registros de la tabla Sucursal
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (1,'Farmacia San Juan','Obregón',83,69,'Roma Norte','Jalisco','''5173477437''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (2,'Farmacia San Pedro','Hidalgo',86,82,'Roma Norte','Tamaulipas','''+70054155032''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (3,'Farmacia La Paz','Hidalgo',67,15,'Roma Norte','Quintana Roo','''3321912770''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (4,'Farmacia San Lucas','Zaragoza',7,70,'Roma Norte','Colima','''+185983794683''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (5,'Farmacia Guadalajara','Hidalgo',38,79,'Condesa','Sonora','''2635939426''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (6,'Farmacia del Sol','Obregón',44,43,'Lomas de Chapultepec','San Luis Potosí','''+66062685623''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (7,'Farmacia San Lucas','Zaragoza',4,89,'Lomas de Chapultepec','Sonora','''+1633565038691''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (8,'Farmacia San Miguel','Revolución',52,19,'Cuajimalpa','San Luis Potosí','''7824827308''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (9,'Farmacia San Lorenzo','Zaragoza',72,96,'Roma Norte','Baja California','''1609621754''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (10,'Farmacia San Rafael','Independencia',66,51,'San Pedro','Hidalgo','''+502189164208''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (11,'Farmacia San Lorenzo','Zaragoza',43,30,'Interlomas','Yucatán','''+4991175027385''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (12,'Farmacia La Paz','Morelos',89,3,'Lomas de Chapultepec','Hidalgo','''+3402704916229''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (13,'Farmacia San Pablo','Morelos',12,65,'Polanco','Puebla','''+01009721868''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (14,'Farmacia San Antonio','Zaragoza',78,98,'Bosques de Chapultepec','Chihuahua','''0340452306''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (15,'Farmacia San Juan','Callejón del Beso',7,51,'Interlomas','Baja California Sur','''0095519916''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (16,'Farmacia San Pablo','Guerrero',65,42,'Del Valle','Baja California','''+707335462582''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (17,'Farmacia San José','Revolución',64,65,'Coyoacan','Aguascalientes','''7026314686''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (18,'Farmacia San José','Hidalgo',92,19,'Cuajimalpa','Tamaulipas','''+606115077375''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (19,'Farmacia Santa Ana','Guerrero',77,90,'San Pedro','Chiapas','''+106722153144''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (20,'Farmacia del Sol','Juárez',9,90,'Tlalpan','Jalisco','''1952530106''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (21,'Farmacia Guadalajara','Juárez',74,1,'Bosques de Chapultepec','Tamaulipas','''5428829966''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (22,'Farmacia San Lucas','Hidalgo',33,33,'Coyoacan','Quintana Roo','''0817650242''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (23,'Farmacia San Rafael','Guerrero',97,60,'Polanco','Oaxaca','''+59820893237''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (24,'Farmacia San Lucas','Allende',28,75,'Polanco','Chihuahua','''3180487201''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (25,'Farmacia San Miguel','Lázaro Cárdenas',11,78,'Lomas de Chapultepec','Aguascalientes','''+39646007835''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (26,'Farmacia San Ignacio','Guerrero',93,10,'San Pedro','Hidalgo','''+66800105724''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (27,'Farmacia San Ignacio','Galeana',84,76,'Polanco','Aguascalientes','''+187881889461''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (28,'Farmacia San Antonio','Revolución',75,50,'La Joya','Guerrero','''+42350649974''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (29,'Farmacia San Antonio','Madero',21,27,'Roma Norte','Querétaro','''+2667599578974''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (30,'Farmacia San Rafael','Morelos',100,76,'Roma Norte','Coahuila','''6547210733''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (31,'Farmacia San Miguel','Morelos',58,46,'Del Valle','Veracruz','''+148041288051''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (32,'Farmacia San Lucas','Morelos',79,31,'La Joya','Chiapas','''1405477956''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (33,'Farmacia San Antonio','Callejón del Beso',39,49,'Condesa','Baja California Sur','''3936937031''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (34,'Farmacia Santa Ana','Guerrero',34,3,'San Pedro','San Luis Potosí','''+8307507863793''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (35,'Farmacia La Paz','Obregón',22,90,'San Pedro','Hidalgo','''2247817231''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (36,'Farmacia San Miguel','Obregón',11,53,'Polanco','Hidalgo','''+369369730943''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (37,'Farmacia San José','Allende',38,64,'Polanco','Hidalgo','''8146351727''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (38,'Farmacia Santa Ana','Zaragoza',4,70,'Santa Fe','Guanajuato','''8173725971''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (39,'Farmacia San Ignacio','Galeana',98,51,'Interlomas','Baja California Sur','''9807731867''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (40,'Farmacia del Sol','Obregón',17,42,'Coyoacan','Tlaxcala','''+83989446757''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (41,'Farmacia La Paz','Zaragoza',67,67,'Coyoacan','Guanajuato','''+5397277755446''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (42,'Farmacia San Rafael','Lázaro Cárdenas',56,100,'Del Valle','Baja California Sur','''5324835208''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (43,'Farmacia San Pedro','Morelos',54,18,'Polanco','Michoacán','''+0266990554768''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (44,'Farmacia San Pedro','Obregón',1,84,'Tlalpan','Querétaro','''0155539446''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (45,'Farmacia San Pablo','Carranza',85,89,'Condesa','Aguascalientes','''+7698735238392''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (46,'Farmacia San Antonio','Carranza',36,69,'La Joya','Oaxaca','''6633958124''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (47,'Farmacia San Antonio','Zaragoza',77,95,'San Pedro','Zacatecas','''+64178234428''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (48,'Farmacia San Pedro','Morelos',14,51,'Polanco','San Luis Potosí','''+78887031241''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (49,'Farmacia San Pedro','Carranza',43,28,'Tlalpan','Hidalgo','''1705649755''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (50,'Farmacia San Lucas','Revolución',15,21,'Cuajimalpa','Chiapas','''+0656944515673''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (51,'Farmacia Santa Ana','Revolución',72,84,'Polanco','Querétaro','''8941539334''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (52,'Farmacia San Lucas','Lázaro Cárdenas',95,83,'Tlalpan','Sonora','''0295330553''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (53,'Farmacia Guadalajara','Revolución',36,58,'Roma Norte','Aguascalientes','''+66366050441''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (54,'Farmacia San Antonio','Carranza',15,98,'Roma Norte','Tamaulipas','''5224741965''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (55,'Farmacia La Paz','Carranza',86,39,'Interlomas','Hidalgo','''9760792680''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (56,'Farmacia Santa Ana','Callejón del Beso',58,13,'Condesa','Tlaxcala','''+2824089689022''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (57,'Farmacia San Pablo','Benito Juárez',55,12,'La Joya','Tabasco','''+2821009476271''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (58,'Farmacia Guadalajara','Zaragoza',54,48,'Cuajimalpa','Campeche','''+3872482052257''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (59,'Farmacia San Pablo','Madero',26,74,'Napoles','Chihuahua','''8184841092''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (60,'Farmacia del Sol','Benito Juárez',95,21,'Cuajimalpa','Guerrero','''+49615412170''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (61,'Farmacia San Lucas','Callejón del Beso',54,86,'San Pedro','Michoacán','''+74380204679''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (62,'Farmacia San Pedro','Carranza',85,100,'San Pedro','Nayarit','''0038118585''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (63,'Farmacia San Pedro','Callejón del Beso',30,65,'Satelite','Quintana Roo','''+87586040498''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (64,'Farmacia Santa Ana','Galeana',75,100,'Del Valle','Querétaro','''+857907330500''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (65,'Farmacia Santa Ana','Allende',56,14,'Satelite','Nuevo León','''5886077657''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (66,'Farmacia Guadalajara','Benito Juárez',93,95,'Bosques de Chapultepec','Sonora','''+37085487392''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (67,'Farmacia San Ignacio','Carranza',41,14,'Satelite','Zacatecas','''+4914429724768''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (68,'Farmacia San Pablo','Revolución',64,89,'Cuajimalpa','San Luis Potosí','''5023933723''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (69,'Farmacia San Ignacio','Zaragoza',87,58,'La Joya','Tlaxcala','''7754601734''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (70,'Farmacia San Rafael','Galeana',98,88,'Tlalpan','Tamaulipas','''+3266068461929''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (71,'Farmacia Guadalajara','Benito Juárez',78,64,'Napoles','Yucatán','''+278935975126''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (72,'Farmacia San Miguel','Obregón',62,88,'Santa Fe','Hidalgo','''6452458779''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (73,'Farmacia San Lorenzo','Juárez',44,33,'Condesa','Chiapas','''2610460534''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (74,'Farmacia San Juan','Callejón del Beso',87,4,'Lomas de Chapultepec','Tamaulipas','''6374942062''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (75,'Farmacia San Miguel','Callejón del Beso',42,92,'Roma Norte','Tlaxcala','''+680135709279''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (76,'Farmacia del Sol','Callejón del Beso',15,89,'San Pedro','Sonora','''4765324728''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (77,'Farmacia San Ignacio','Revolución',58,31,'Coyoacan','Tabasco','''+3358432197652''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (78,'Farmacia Santa Ana','Guerrero',29,70,'Condesa','Hidalgo','''+4239129914778''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (79,'Farmacia San Miguel','Independencia',39,89,'Tlalpan','Nuevo León','''2163926384''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (80,'Farmacia San Antonio','Independencia',81,60,'Santa Fe','Sinaloa','''1834105549''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (81,'Farmacia San Antonio','Guerrero',23,35,'Bosques de Chapultepec','Campeche','''+21312069956''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (82,'Farmacia San Lucas','Guerrero',17,87,'Del Valle','Chihuahua','''1682748719''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (83,'Farmacia del Sol','Carranza',32,16,'San Pedro','Veracruz','''7907503534''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (84,'Farmacia San Lorenzo','Benito Juárez',4,16,'Interlomas','Morelos','''5474541373''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (85,'Farmacia San Juan','Callejón del Beso',18,85,'Polanco','Morelos','''0079285445''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (86,'Farmacia San José','Madero',2,86,'Lomas de Chapultepec','Baja California Sur','''+734992201096''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (87,'Farmacia San José','Morelos',43,24,'Napoles','Jalisco','''+813053574875''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (88,'Farmacia San Pablo','Lázaro Cárdenas',30,34,'Roma Norte','Baja California','''+454451329093''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (89,'Farmacia La Paz','Hidalgo',100,10,'San Pedro','Tabasco','''7488246774''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (90,'Farmacia San Lucas','Obregón',4,99,'Lomas de Chapultepec','Sinaloa','''+54274832197''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (91,'Farmacia San Juan','Callejón del Beso',13,34,'Santa Fe','Baja California Sur','''+9819466052593''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (92,'Farmacia San Lorenzo','Galeana',54,91,'Santa Fe','Chihuahua','''6896029190''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (93,'Farmacia La Paz','Allende',13,67,'Lomas de Chapultepec','Tabasco','''6737750738''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (94,'Farmacia San Antonio','Obregón',70,21,'Roma Norte','Quintana Roo','''+678519154512''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (95,'Farmacia San Rafael','Juárez',5,9,'San Pedro','Guerrero','''3715724873''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (96,'Farmacia San Lorenzo','Hidalgo',67,23,'Del Valle','San Luis Potosí','''+20948001574''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (97,'Farmacia del Sol','Obregón',63,85,'Lomas de Chapultepec','Hidalgo','''0903045920''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (98,'Farmacia San Vicente','Independencia',19,75,'Lomas de Chapultepec','Veracruz','''+529756501953''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (99,'Farmacia San Lorenzo','Obregón',22,34,'Condesa','Guanajuato','''4651832988''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (100,'Farmacia Guadalajara','Allende',30,15,'Lomas de Chapultepec','Colima','''+4564180997933''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (101,'Farmacia del Sol','Allende',79,93,'Napoles','Coahuila','''9392040555''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (102,'Farmacia San Antonio','Obregón',38,100,'Napoles','Tamaulipas','''+21656778216''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (103,'Farmacia San Ignacio','Juárez',50,5,'Santa Fe','Tamaulipas','''+79676233733''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (104,'Farmacia La Paz','Benito Juárez',61,46,'Lomas de Chapultepec','Querétaro','''2524910969''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (105,'Farmacia del Sol','Hidalgo',35,50,'Coyoacan','Tlaxcala','''6964242234''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (106,'Farmacia Santa Ana','Madero',78,12,'Del Valle','Michoacán','''+375513847393''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (107,'Farmacia San Lucas','Lázaro Cárdenas',44,64,'Interlomas','Baja California','''+8575460113046''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (108,'Farmacia Guadalajara','Revolución',85,30,'Condesa','Sinaloa','''6307865224''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (109,'Farmacia Santa Ana','Morelos',8,24,'Condesa','Hidalgo','''+715430702182''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (110,'Farmacia San Rafael','Morelos',39,37,'Napoles','Veracruz','''2881005477''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (111,'Farmacia San Lorenzo','Guerrero',23,12,'San Pedro','Baja California Sur','''4082774134''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (112,'Farmacia San José','Madero',35,5,'Tlalpan','Sinaloa','''+733190311050''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (113,'Farmacia del Sol','Allende',34,36,'Coyoacan','Jalisco','''7115379100''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (114,'Farmacia San Lorenzo','Juárez',43,51,'Coyoacan','Zacatecas','''+921619106830''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (115,'Farmacia San Pablo','Lázaro Cárdenas',7,20,'Satelite','Tlaxcala','''+21958561197''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (116,'Farmacia San Pedro','Obregón',90,66,'Bosques de Chapultepec','Durango','''4458608026''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (117,'Farmacia La Paz','Obregón',82,17,'Lomas de Chapultepec','Durango','''3789603093''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (118,'Farmacia San Pablo','Madero',60,70,'Condesa','Chiapas','''+1656815845470''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (119,'Farmacia San Lucas','Allende',36,9,'Satelite','Chihuahua','''5937691377''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (120,'Farmacia San Lucas','Benito Juárez',95,73,'Del Valle','Quintana Roo','''4697239693''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (121,'Farmacia San Lorenzo','Galeana',53,26,'Satelite','Guerrero','''+7686135665800''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (122,'Farmacia San Vicente','Guerrero',61,52,'Del Valle','Chihuahua','''9136541543''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (123,'Farmacia San Lorenzo','Revolución',74,63,'Lomas de Chapultepec','Nuevo León','''5397082443''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (124,'Farmacia San Ignacio','Madero',100,81,'Polanco','Tlaxcala','''6601248118''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (125,'Farmacia San Rafael','Hidalgo',34,34,'Lomas de Chapultepec','Tabasco','''6546523887''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (126,'Farmacia San Ignacio','Benito Juárez',88,32,'Interlomas','Yucatán','''3859138927''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (127,'Farmacia Guadalajara','Galeana',81,51,'San Pedro','Michoacán','''0842175566''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (128,'Farmacia San Vicente','Zaragoza',16,41,'Interlomas','Morelos','''7688792486''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (129,'Farmacia Santa Ana','Obregón',45,96,'Coyoacan','Zacatecas','''2662036937''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (130,'Farmacia Guadalajara','Benito Juárez',32,3,'Napoles','Chihuahua','''+03012372418''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (131,'Farmacia La Paz','Allende',31,20,'Bosques de Chapultepec','Morelos','''+78751343297''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (132,'Farmacia San Ignacio','Independencia',35,20,'Tlalpan','Guanajuato','''8575798920''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (133,'Farmacia del Sol','Independencia',40,43,'Napoles','Campeche','''+3701930889183''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (134,'Farmacia San Juan','Juárez',86,76,'Lomas de Chapultepec','Querétaro','''1695436384''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (135,'Farmacia San Antonio','Hidalgo',41,7,'Condesa','Puebla','''+338366242151''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (136,'Farmacia San Lucas','Hidalgo',51,87,'Bosques de Chapultepec','Quintana Roo','''+6201731621176''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (137,'Farmacia San Vicente','Carranza',91,27,'Polanco','Colima','''6146574694''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (138,'Farmacia San Miguel','Zaragoza',92,39,'Tlalpan','Veracruz','''+2134615715208''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (139,'Farmacia San Antonio','Obregón',61,60,'Santa Fe','Tlaxcala','''+845789094305''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (140,'Farmacia San Ignacio','Hidalgo',99,53,'La Joya','Durango','''+051386931207''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (141,'Farmacia San Lorenzo','Madero',49,11,'Napoles','Nayarit','''+09723402833''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (142,'Farmacia San Lucas','Zaragoza',49,51,'Polanco','Oaxaca','''9474819105''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (143,'Farmacia San Lucas','Independencia',94,40,'Cuajimalpa','Durango','''0558126545''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (144,'Farmacia Guadalajara','Revolución',26,65,'La Joya','Zacatecas','''2728557971''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (145,'Farmacia San Miguel','Hidalgo',61,38,'Interlomas','Jalisco','''+4640976704379''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (146,'Farmacia del Sol','Revolución',42,91,'Napoles','Baja California Sur','''0685769878''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (147,'Farmacia San Lucas','Callejón del Beso',93,35,'Condesa','Baja California','''8480335113''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (148,'Farmacia San Lucas','Benito Juárez',73,7,'Roma Norte','Morelos','''+16042811419''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (149,'Farmacia San José','Revolución',49,84,'Del Valle','Yucatán','''+0922881703840''');
INSERT INTO Sucursal(IdSucursal,NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES (150,'Farmacia San Vicente','Morelos',95,95,'Bosques de Chapultepec','Chiapas','''+482660697438''');


--150 registros de la tabla Clinica


--150 registros de la tabla Medico


--150 registros de la tabla Telefonos_Medico


-- Tablas necesarias para ejecutar el script Query.sql

